ALTER TABLE ONLY voyages 
ADD COLUMN adlt1imp integer,
ADD COLUMN slavmax1 integer,
ADD COLUMN slavmax3 integer,
ADD COLUMN slavmax7 integer,
ADD COLUMN adlt2imp integer,
ADD COLUMN chil2imp integer,
ADD COLUMN male2imp integer,
ADD COLUMN feml2imp integer;