INSERT INTO faqs_categories (id, name, order_num) VALUES (1, 'GENERAL', 1);
INSERT INTO faqs_categories (id, name, order_num) VALUES (2, 'VARIABLES', 3);
INSERT INTO faqs_categories (id, name, order_num) VALUES (3, 'QUERIES (VOYAGE DATABASE)', 4);
INSERT INTO faqs_categories (id, name, order_num) VALUES (4, 'RESULTS (VOYAGE DATABASE)', 5);
INSERT INTO faqs_categories (id, name, order_num) VALUES (5, 'SUMMARY STATISTICS (VOYAGES DATABASE)', 6);
INSERT INTO faqs_categories (id, name, order_num) VALUES (6, 'TABLES', 7);
INSERT INTO faqs_categories (id, name, order_num) VALUES (7, 'CUSTOM GRAPHS (VOYAGES DATABASE)', 8);
INSERT INTO faqs_categories (id, name, order_num) VALUES (8, 'TIMELINE', 9);
INSERT INTO faqs_categories (id, name, order_num) VALUES (9, 'MAPS', 10);
INSERT INTO faqs_categories (id, name, order_num) VALUES (10, 'DOWNLOADS', 11);
INSERT INTO faqs_categories (id, name, order_num) VALUES (11, 'CONTRIBUTE', 12);
INSERT INTO faqs_categories (id, name, order_num) VALUES (12, 'ESSAYS', 13);
INSERT INTO faqs_categories (id, name, order_num) VALUES (13, 'ESTIMATES', 14);
INSERT INTO faqs_categories (id, name, order_num) VALUES (14, 'IMAGES', 15);
INSERT INTO faqs_categories (id, name, order_num) VALUES (15, 'AFRICAN NAMES DATABASE', 16);
INSERT INTO faqs_categories (id, name, order_num) VALUES (16, 'EDUCATIONAL MATERIALS', 17);
INSERT INTO faqs_categories (id, name, order_num) VALUES (17, 'CITING THE VOYAGES WEBSITE', 2);
INSERT INTO faqs_categories (id, name, order_num) VALUES (18, 'OTHER', 18);