<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://tas.library.emory.edu" prefix="s"%>
<%@ taglib uri="http://myfaces.apache.org/tomahawk" prefix="t"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<title>Essays</title>
	
	<link href="../styles/main.css" rel="stylesheet" type="text/css">
	<link href="../styles/main-menu.css" rel="stylesheet" type="text/css">
	
	<link href="../styles/expandable-box.css" rel="stylesheet" type="text/css">
	<link href="../styles/assessment-expandable-box.css" rel="stylesheet" type="text/css">

	<link href="../styles/assessment.css" rel="stylesheet" type="text/css">
	<link href="../styles/assessment-essays.css" rel="stylesheet" type="text/css">

	<script src="../scripts/utils.js" language="javascript" type="text/javascript"></script>
	<script src="../scripts/main-menu.js" language="javascript" type="text/javascript"></script>

</head>
<body>
<f:view>
<h:form id="form">

	<f:loadBundle basename="SlaveTradeResources" var="res"/>

	<div id="top-bar">
		<table border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td><a href="../index.faces"><img src="../images/logo.png" border="0" width="300" height="100"></a></td>
			<td class="main-menu-container"><s:mainMenuBar menuItems="#{MainMenuBean.mainMenu}" activeSectionId="assessment" activePageId="essays" /></td>
		</tr>
		</table>
	</div>
	
	<div id="content">
	
		<table border="0" cellspacing="0" cellpadding="0" class="essays-layout">
		<tr>
			<td class="essays-left-column">

				<s:expandableBox text="Table of Content">
					<f:verbatim escape="false">
						<ol class="toc">
							<li class="current-essay">Introductory essay</li>
							<li>Slavery and Freedom in the Early Modern World</li>
							<li>The English, the Dutch, and Transoceanic Migration</li>
							<li>Europeans and African Slavery in the Americas</li>
							<li>Gender and Slavery in the Modern Atlantic World</li>
							<li>Africa and Europe in the Early Modern Era</li>
							<li>The African Impact on the Tranatlatic Slave Trade</li>
							<li>The English Plantation Americas in Comparative Perspective</li>
							<li>Ethnicity in the Early Modern Atlatic World</li>
							<li>Europe and the Atlantic Slave systems</li>
						</ol>
					</f:verbatim>
				</s:expandableBox>
				
				<br>
				
			</td>
			<td class="essays-right-column">
			
			<h1>Introductory essay</h1>

			<p>The transatlantic slave trade was the largest long-distance coerced movement of people in history and, prior to the mid-nineteenth century, formed the major demographic well-spring for the re-peopling of the Americas following the collapse of the Amerindian population. Cumulatively, as late as 1820, nearly four Africans had crossed the Atlantic for every European, and, given the differences in the sex ratios between European and African migrant streams, about four out of every five females that traversed the Atlantic were from Africa. From the late fifteenth century the Atlantic Ocean, once a formidable barrier that prevented regular interaction between those peoples inhabiting the four continents it touched, became a commercial highway that integrated the histories of Africa, Europe, and the Americas for the first time. As the above figures suggest, slavery and the slave trade were the linchpins of this process. With the decline of the Amerindian population labor from Africa formed the basis of the exploitation of the gold and agricultural resources of the export sectors of the Americas, with sugar plantations absorbing well over two thirds of slaves carried across the Atlantic by the major European and Euro-American powers. For several centuries slaves were the most important reason for contact between Europeans and Africans.</p>

			<p>What can explain this extraordinary migration organized initially on a continent where the institution of slavery had declined or totally disappeared in the centuries prior to Columbian contact, and where, even when it had existed, slavery had never been confined to one group of people? To pose the question differently, why slavery, and why were the slaves carried across the Atlantic exclusively African? The short answer to the first of these two questions is that European expansion to the Americas was to mainly tropical and semi-tropical areas. Several products that were either unknown to Europeans (like tobacco), or occupied a luxury niche in pre-expansion European tastes (like gold or sugar), now fell within the capacity of Europeans to produce more abundantly. But while Europeans could control the production of such exotic goods, it became apparent in the first two centuries after Columbian contact that they chose not to supply the labor that would make such output possible. Free European migrants and indentured servants never traveled across the Atlantic in sufficient numbers to meet the labor needs of expanding plantations. Convicts and prisoners – the only Europeans that were ever forced to migrate – were much fewer in numbers again. Slavery, or some form of coerced labor was the only possible option if European consumers were to gain access to more tropical produce and precious metals.</p>

			<p>But why were the slaves always African? One possible answer draws on the different values of societies around the Atlantic and, more particularly, the way groups of people involved in creating a transatlantic community saw themselves in relation to others – in short, how they defined their identity. Ocean-going technology brought Europeans into large scale face-to-face contact with peoples who were culturally and physically more different from themselves than any others with whom they had interacted in the previous millennium. In neither Africa, nor Asia could Europeans initially threaten territorial control - with the single and limited exception of western Angola. African capacity to resist Europeans ensured that sugar plantations were established in the Americas rather than in Africa. But if Africans, aided by tropical pathogens, were able to resist the potential invaders, some Africans were prepared to sell slaves to Europeans for use in the Americas. As this suggests, European domination of Amerindians was complete. Indeed, from the European perspective it was much too complete. The epidemiological impact of the Old World destroyed not only native American societies, but also a potential labor supply.</p>

			<p>Every society in history before 1900 provided at least an unthinking answer to the question of which groups are to be considered eligible for enslavement, and normally they did not recruit heavily from their own community. A revolution in ocean-going technology gave Europeans the ability to get continuous access to remote peoples and move them against their will over very long distances. Strikingly, it was much cheaper to obtain slaves in Europe than to send a vessel to an epidemiological hostile coast in Africa without proper harbors and remote from European political financial and military power. That this option was never seriously considered suggests a European inability to enslave other Europeans. Except for a few social deviants, neither Africans nor Europeans would enslave members of their own societies, but in the early modern period, Africans had a somewhat narrower conception of who was eligible for enslavement than had Europeans. It was this difference in definitions in eligibility for enslavement which explains the dramatic rise of the transatlantic slave trade. Slavery, which had disappeared from north-west Europe long before this point, exploded into a far greater significance and intensity than it had possessed at any point in human history. The major cause was a dissonance in African and European ideas of eligibility for enslavement at the root of which lies culture or societal norms, not easily tied to economics. Without this dissonance, there would have been no African slavery in the Americas. The slave trade was thus a product of differing constructions of social identity and the ocean-going technology that brought Atlantic societies into sudden contact with each other. </p>

			<p>The transatlantic slave trade therefore grew from a strong demand for labor in the Americas driven consumers of plantation produce and precious metals, initially in Europe. Because Amerindians died in large numbers, and insufficient numbers of European were prepared to cross the Atlantic, the form that this demand took was shaped by conceptions of social identity on four continents which ensured that the labor would comprise mainly slaves from Africa. But the central question of which peoples from Africa went to a given region of the Americas, and which group of Europeans or their descendants organized such a movement cannot be answered without an understanding of the wind and ocean currents of the North and South Atlantics. There are two systems of wind and ocean currents in the North and South Atlantic that follow the pattern of giant wheels - one lies north of the equator turns clockwise, while its counterpart to the south turns counterclockwise.i The northern wheel largely shaped the north European slave trade and was dominated by the English. The southern wheel shaped the huge traffic to Brazil which for three centuries was almost the almost exclusive preserve of the largest slave traders of all, the Portuguese.ii Despite their use of the Portuguese flag, slave traders using the southern wheel ran their business from ports in Brazil, not in Portugal. Winds and currents thus ensured two major slave trades – the first rooted in Europe, the second in Brazil. Winds and currents also ensured that Africans carried to Brazil came overwhelmingly from Angola, with south-east Africa and the Bight of Benin playing smaller roles, and that Africans carried to North America, including the Caribbean, left from mainly West Africa with the Bights of Biafra and Benin and the Gold Coast predominating. Just as Brazil overlapped on the northern system by drawing on the Bight of Benin, the English, French and Dutch carried some slaves from northern Angola into the Caribbean.</p>

			<p>If demand for slave-grown produce, social identity, and the Atlantic environment were three key factors shaping the traffic, the agency of Africans comprised a fourth major influence, but one which has received less attention from historians. The merchants who traded slaves on the coast to European ship captains – for example the Vili traders north of the Congo, the Efik in the Bight of Biafra - and behind them the groups that supplied the slaves, such as the Kingdom of Dahomey, the Aro network and further south, the Imbangala, all had strict conceptions of what made an individual eligible for enslavement. Among such criteria were constructions of gender, definitions of criminal behavior, and conventions for dealing with prisoners of war. The make up of slaves purchased on the Atlantic coast thus reflected whom Africans were prepared to sell as much as whom Euro-American plantation owners wanted to buy. But the victims of the slave trade also had a major impact on the trade. Probably about one in ten slaving voyages experienced major rebellions, the attempts to control which increased the costs of a slave voyage to the point where far fewer slaves entered the traffic than would have been the case without resistance. In addition, vessels from some regions on the coast appear to have been more prone to experience slave uprisings than those from other regions. The rebellion-prone areas were precisely those regions, broadly comprising Upper Guinea (Senegambia, Sierra Leone, and the Windward Coast) which had the least participation in the slave trade. The strong inference is that European slave traders avoided this part of the African coast except in those years when demand for slaves, and their prices were particularly high. </p>

			<p>With the key forces shaping the traffic briefly described, we can now turn to a short narrative of the slave trade. The first Africans forced to work in the New World left from Europe at the beginning of the sixteenth century, not from Africa. There were few vessels that carried only slaves on this early route, so that most would have crossed the Atlantic in smaller groups on vessels carrying many other commodities, rather than dedicated slave ships. Such a slave route was possible because an extensive traffic in African slaves from Africa to Europe and the Atlantic islands had existed for half a century before Columbian contact such that ten percent of the population of Lisbon was black in 1455,iii and black slaves were common on large estates in the Portuguese Algarve. The first slave voyage direct from Africa to the Americas probably sailed in 1526.iv Before mid-century, all transatlantic slave ships sold their slaves in the Spanish Caribbean, with the gold mines in Cibao on Hispaniola emerging as a major purchaser. Cartagena, in modern Columbia, appears as the first mainland Spanish American destination for a slave vessel - in the year 1549.v On the African side the great majority of people entering the early slave trade came from the Upper Guinea coast, and moved through Portuguese factories initially in Arguim, and later the Cape Verde islands. Nevertheless, the 1526 voyage set out from the other major Portuguese factory in West Africa - Sao Tome in the Bight of Biafra – though the slaves almost certainly originated in the Congo.</p>

			<p>The slave traffic to Brazil, eventually accounting for about forty percent of the trade, got underway around 1560. Sugar drove this traffic, as Africans gradually replaced the Amerindian labor force on which the early sugar mills (called engenhos) had drawn over the period 1560 to 1620. By the time the Dutch invaded Brazil in 1630, Pernambuco, Bahia and Rio de Janeiro were supplying almost all of the sugar consumed in Europe and almost all the slaves producing it were African. Consistent with the earlier discussion of Atlantic wind and ocean currents, there were by 1640 two major branches of the transatlantic slave trade operating, one to Brazil, and the other to the mainland Spanish Americas, but together they accounted for less 7,500 departures a year from the whole of sub-Saharan Africa, almost all of them by 1600 from west-central Africa. The sugar complex spread to the eastern Caribbean from the beginning of the 1640s. Sugar consumption steadily increased in Europe, and the slave system began two centuries of westward expansion across tropical and sub-tropical North America.vi At the end of the seventeenth century, gold discoveries in first, Minas Gerais and later in Goias and other parts of Brazil began a transformation of the slave trade which triggered further expansion of the business. In Africa, the Bights of Benin and Biafra became major sources of supply, in addition to Angola, and were joined later by the more marginal provenance zones of Sierra Leone, the Windward Coast and South-east Africa. The volume of slaves carried off reached thirty thousand per annum in the 1690s and eighty-five thousand a century later. More than eight out of ten Africans pulled into the traffic in the era of the slave trade made their journeys in the century and a half after 1700. </p>

			<p>In the second half of the eighteenth century six imperial systems straddled the Atlantic each one sustained by a slave trade. The English, French, Portuguese, Spanish, Dutch, and Danish all operated behind trade barriers (termed mercantilistic restrictions) and produced a range of plantation produce - sugar, rice, indigo, coffee, tobacco, alcohol and some precious metals - though with sugar usually the most valuable. It is extraordinary that consumers’ pursuit of this limited range of exotic consumer goods which collectively added so little human welfare could have generated for so long the horrors and misery of the middle passage and plantation slavery.  Given the dominance of Portuguese and British slave traders, it is not surprising that Brazil and the British Americas received the most Africans, though both nations became adept at supplying foreign slave systems as well. Throughout the slave trade, more than seven out of every ten slaves went to these regions. The French Americas imported about half the slaves that the British did, with the majority going to Saint-Domingue. The Spanish flag, having dominated in the earliest phase of the trade, before retreating in the face of competition, began to expand again in the late nineteenth century with the growth of the Cuban sugar economy. </p>

			<p>Yet, in the next century - between 1750 and 1850 – every one of these empires had either disappeared or become severely truncated. A massive shift to freer trade meant that instead of six plantation empires controlled from Europe there were now only three plantation complexes, two of which—Brazil and the United States—were independent, and the third, Cuba, was far wealthier and more dynamic than its European owner. Extreme specialization now saw the United States producing most of the world’s cotton, Cuba most of the world’s sugar; and Brazil with a similar dominance in coffee. Slaves thus might disembark in six separate jurisdictions in the Americas in the eighteenth century, but by 1850 they went overwhelmingly to only two areas, Brazil and Cuba, given that American cotton planters drew on Africa for almost none of their labor needs, relying instead on natural population growth and a domestic slave trade. Indeed, overall the United States absorbed only 5 percent of the slaves arriving in the Americas. This massive reorganization of the traffic and the rapid natural growth of the US slave population had little immediate impact on the size of the slave trade. The British, US, Danish and Dutch dropped out of the slave trade, but the decade 1821 to 1830 still saw over 80,000 people a year leaving Africa in slave ships. Well over a million more – one tenth of the volume carried off in the slave trade era - followed in the next twenty years.  </p>

			<p>On the African side, the sheer human and environmental diversity of the continent makes it difficult to examine the trade from Africa as a whole. The slave trade did not expand, nor, indeed, decline, in all areas of Africa at the same time. Rather, a series of marked expansions (and declines) in individual regions contributed to a more gradual composite trend for sub-Saharan Africa as a whole. Each region that exported slaves experienced a marked upswing in the amount of slaves it supplied for the transatlantic trade and, from that point, the normal pattern was for a region to continue to export large numbers of slaves for a century or more. The three regions that provided the fewest slaves – Senegambia, Sierra Leone, the Windward Coast – reached these higher levels for much shorter periods. </p>

			<p>By the third quarter of the eighteenth century, all regions had undergone an intense expansion of slave exports. A cargo of slaves could be sought at particular points along the entire Western African coast. As the Brazilian coffee and sugar boom got under way near the end of the eighteenth century, slavers rounded the Cape of Good Hope and traveled as far as southeast Africa to fill their vessel’s hold.  But while the slave trade pervaded much of the African coast, its focus was no less concentrated in particular African regions than it was among European carriers. West Central Africa, the long stretch of coast south of Cape Lopez and stretching to Benguela, sent more slaves than any other part of Africa every quarter century with the exception of a fifty-year period between 1676 and 1725.  From 1751 to 1850, this region supplied nearly half of the entire African labor force in the Americas; in the half century after 1800, West Central Africa sent more slaves than all of the other African regions combined. Overall, the center of gravity of the volume of the trade was located in West Central Africa by 1600. It then shifted northward slowly until about 1730 before gradually returning to its starting point by the mid-nineteenth century.</p>

			<p>Further, slaves left from relatively few ports of embarkation within each African region, even though their origins and ethnicities could be highly diverse. Although Whydah, on the Slave Coast, was once considered the busiest African slaving port on the continent, it now appears that it was surpassed by Luanda, in West Central Africa, and by Bonny, in the Bight of Biafra. Luanda alone dispatched some 1.3 million slaves and these three most active ports together accounted for 2.2 million slave departures. The trade from each of these ports assumed a unique character and followed very different temporal profiles. Luanda actively participated in the slave trade from as early as the 1570s, when the Portuguese established a foothold there, through the nineteenth century. Whydah supplied slaves over a shorter period, for about two centuries, and was a dominant port for only thirty years prior to 1727. Bonny, probably the second largest point of embarkation in Africa, sent four out of every five of all the slaves it ever exported in just the eighty years between 1760 and 1840. It is not surprising therefore that some systematic links between Africa and the Americas can be perceived. As research on the issue of transatlantic connections has progressed, it has become clear that the distribution of Africans in the New World is no more random than the distribution of Europeans. Eighty percent of the slaves who went to southeast Brazil were taken from West Central Africa. Bahia traded in similar proportions with the Bight of Benin. Cuba represents the other extreme: no African region supplied more than 28 percent of the slave population in this region. Most American import regions fell between these examples, drawing on a mix of coastal regions that diversified as the trade from Africa grew to incorporate new peoples.</p>

			<p>Whatever the route taken, conditions on board reflected the outsider status of those held below deck. No European, whether convict, indentured servant or destitute free migrant, was ever subjected to the environment which greeted the typical African slave upon embarkation. The sexes were separated, kept naked, packed close together and the men were chained for long periods. No less than 26 percent of those on board were classed as children, a ratio that no other pre 20th C migration could come close to matching. Except for the illegal period of the trade when conditions at times became even worse, slave traders typically packed two slaves per ton. While a few voyages sailing from Upper Guinea could make a passage to the Americas in three weeks, the average duration from all regions of Africa was just over two months. Most of the space on a slave ship was absorbed by casks of water.vii Crowded vessels sailing to the Caribbean from West Africa first had to sail south before turning north-west and passing through the doldrums. In the nineteenth century improvements in sailing technology eventually cut the time in half, but mortality remained high in this period because of the illegal nature of the business. Throughout the slave trade era, filthy conditions ensured endemic gastro-intestinal diseases, and a range of epidemic pathogens that together with periodic breakouts of violent resistance meant that between 12 and 13 percent of those embarked did not survive the voyage. Modal mortality fell well below mean mortality as catastrophes on a relatively few voyages drove up average shipboard deaths. Crew mortality as a percentage of those going on board, matched slave mortality over the course of the voyage, but as slaves were there for a shorter period of time than the crew, mortality rates for slaves (over time) were the more severe. The eighteenth century world was violent and life-expectancy was short everywhere given that the global mortality revolution was still over the horizon, but the human misery quotient generated by the forced movement of millions of people in slave ships cannot have been matched by any other human activity.</p>

			<p>When the transatlantic slave trade came to an end, it did so rather suddenly. When the Brazilian authorities began arresting slave ships at the end of 1850, the volume of the traffic of the traffic slipped back to levels not seen for two centuries, and the last transatlantic slave expedition – to Cuba and probably from the Congo River – completed its voyage in 1867. For the last two decades of the traffic, only the Bight of Benin and the Congo region were heavily engaged in the trade. Nevertheless over the whole period of the trade some 12.5 million slaves had been shipped from Africa and 10.7 million had arrived in the Americas, likely the most costly in human life of all of long-distance global migrations. Why the rather sudden end to a business which despite its high morbidity and mortality, had been seen as no different from any other until the late eighteenth century?  This is a very large question which it would be presumptuous to attempt to answer here given the massive literature on the topic. One point is clear, the traffic did not fade away; rather it was suppressed at a time when the prices of slaves were rising to levels that had never previously attained. The economic imperatives clearly pointed to a continuation of the trade and without attempts to suppress it, the majority of the millions of people who crossed the Atlantic between 1820 and 1920 might well have been African rather than European, and enslaved rather than free. As it was by the 1850s, for most in the Atlantic world, the slave trade had become a despised and illegal traffic. By the 1840s, the British had committed ten percent of their naval resources to suppressing the trade; a scant half century earlier they were the leading slave trading nation. </p>

			<p>One contributing factor to this shift is an extension of an argument made earlier in this essay. In one sense abolition was a shift in conceptions of who was eligible for enslavement. The definition of eligibility had certainly included other Europeans prior to the thirteenth century as a thriving slave trade within Europe saw people from the North captured by other Europeans and carried for sale in the South, many, ultimately, to the prosperous Islamic areas. This situation was little different from what existed in Africa, but, as already noted, by the time of Columbian contact, eligibility had come to exclude other Europeans. Africa was a much larger land mass and home to human populations of more diversity than could be found in any other area of similar size on the globe. It is not surprising that Africans did not have a continent-wide conception of insidership – that is peoples whom one could not enslave.  In one sense, the massive and unprecedented flow of racially exclusive coerced labor across the Atlantic is perhaps the result of the differential pace in the evolution of a cultural pan-Europeanness on the one hand, and a pan-Africanism on the other. An interlude of two or three centuries between the former and the latter provided a window of opportunity in which the slave trade rose and fell dramatically. For four centuries from the mid-fifteenth century to 1867, Europeans were not prepared to enslave each other, but were prepared to buy Africans and keep them and their descendants enslaved. Given that “Africa“ scarcely existed as a concept for Africans in any sense before the nineteenth century, most people living in the sub-continent south of the Sahara (as in Europe) were prepared to enslave others from adjacent or distant societies. The corollary of this is that all peoples in history – even the most energetic of slave traders - have had strict definitions of eligibility – and thus ineligibility. “Ineligibility” implies that some basis for abolition has always existed. Between the fifteenth and nineteenth centuries, Europe and Africa simply had different conceptions of the peoples for whom slavery (and the slave trade) were inappropriate.</p>

			<p>In the Atlantic after 1492 oceans that had hermetically sealed peoples and cultures from each other sprouted sea-lanes almost overnight. Cultural accommodation between peoples, in this case between Europeans and non-Europeans, always took time. The big difference was that before Columbus, migrations had been gradual and tended to move outwards from the more to the less densely populated parts of the globe. But Columbian contact was sudden, and inhibited any gradual adjustment, cultural as well as epidemiological. A merging of perceptions of right and wrong, group identities, and relations between the sexes, to look only at the top of a very long list of social values, could not be expected to occur quickly in a post-Columbian world. In short, cultural adjustment could not keep pace with transportation technology. The result was first the rise, and then, as perceptions of the insider-outsider divide slowly changed, the fall, of the transatlantic trade in enslaved Africans.</p>

			<p>During the long coercive interlude of forced transatlantic migration European and African conceptions of self and community (and eligibility for ensalvement) did not remain static. On the African side, the major effect of the African-European exchange was to encourage an elementary pan-Africanism, at least among victims. The initial and unintentional impact of European sea-borne contact was to force non-elite Africans to think of themselves as part of a wider African group. Initially, this group might be Igbo, or Yoruba, and soon, in addition, blacks as opposed to whites. At the most elemental level by the late eighteenth century the slaves at James Island vowed to drink the blood of the Awhitemen@.  In Gorée, a little later, one third of the slaves in a carefully planned conspiracy, Awould go in the village and be dispersed to massacre the whites@. When asked “[w]hether it were true that they had planned to massacre all the whites of the island....[t]he two leaders, far from denying the fact or looking for prevarication, answered with boldness and courage: that nothing was truer”.viii Many similar incidents could be cited from the Americas side of the Atlantic. And on board a slave ship with all the slaves always black, and the crew largely white, skin colour defined ethnicity.</p>

			<p>Awareness of the insider-outsider divide within Europe coincided with the onset of the struggle to suppress first, the slave trade, and then slavery itself. Early in the British campaign to suppress the slave trade, Charles James Fox, a British statesman, posed a question for the House of Commons that he described as “the foundation for the whole business.” How would members of Parliament react, he asked, if “a Bristol ship were to go to any part of France…and the democrats (there) were to sell the aristocrats, or vice versa, to be carried off to Jamaica….to be sold for slaves?” The very posing of this question – and this is the earliest documented example from someone close to power – meant that the issue was not whether the system was to be questioned, but rather when it would end. In the same year, the Danes passed legislation ensuring their own slave trade would become illegal in 1802. In 1807, the British and US governments made the trade illegal. Beginning in 1810, the British established a network of treaties that allowed their naval vessels to detain the slave ships of other nations. The decisive actions against the traffic nevertheless did not come until the mid 1840s and again in 1851, when the Cuban and Brazilian governments respectively took serious action against the slave trade. In effect, the traffic could be halted only by the intervention of the governments of regions that were either exporting or importing slaves; it could not be halted by naval action alone. Nevertheless, naval intervention did result in the capture of nearly 2,000 slave vessels after 1808.ix Only 544 of these had slaves on board at the time of capture, but their 125,000 captives (or strictly, re-captives) were diverted from the sugar and coffee plantations for which they were intended, and for the most part ended their lives with choices they did not have prior to their re-capture.</p>

			<p>Between the 1840s and 1850s, the traffic declined from an average of 50,000 a year to 16,000 and after 1860 to half this. It was carried on under the Spanish and Portuguese flags, and sometimes under no flag at all. By now all governments were cooperating to suppress the traffic. From one perspective the slave trade dragged on for many decades after the first action was taken against it in 1792. From another, it disappeared in less than a century after millennia during which slavery and slave trading had been regarded as normal as growing food. Not surprisingly, a few decades beyond 1867 saw other (though much smaller) varieties of long-distance movement of coerced labor disappear as well. The flow of contract laborers from Asia to the Americas ended in 1917, the last convict dispatched to exile in the Americas returned from Devil’s Island to France in 1952. Notwithstanding the horrors of forced labor of the twentieth century and the ongoing smuggling of illegal laborers into developed countries, often under terms debt slavery, it is inconceivable that a slave traffic could reappear as a central social institution. </p>
			
			</td>
		
		</tr>
		</table>
		
	</div>

</h:form>
	
</f:view>
</body>
</html>