INSERT INTO regions (region_id, name, area_id) VALUES (1  ,'France', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (2  ,'Britain', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (3  ,'Netherlands', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (4  ,'Spain', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (5  ,'Portugal', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (6  ,'Denmark', 1);
INSERT INTO regions (region_id, name, area_id) VALUES (7  ,'Rhode Island', 2);
INSERT INTO regions (region_id, name, area_id) VALUES (8  ,'Non RI New England', 2);
INSERT INTO regions (region_id, name, area_id) VALUES (9  ,'Maryland',			2);
INSERT INTO regions (region_id, name, area_id) VALUES (10  ,'Virginia',			2);
INSERT INTO regions (region_id, name, area_id) VALUES (11  ,'Carolinas',			2);
INSERT INTO regions (region_id, name, area_id) VALUES (12  ,'Georgia',			2);
INSERT INTO regions (region_id, name, area_id) VALUES (13  ,'Mississippi Delta' 2  );
INSERT INTO regions (region_id, name, area_id) VALUES (14  ,'New York'			2  );
INSERT INTO regions (region_id, name, area_id) VALUES (15  ,'Pennsylva nia, Del., N.J.'			2  );
INSERT INTO regions (region_id, name, area_id) VALUES (16  ,'Guadeloupe',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (18  ,'Dutch Caribbean'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (19  ,'Off-shore Atlantic'			7);
INSERT INTO regions (region_id, name, area_id) VALUES (20  ,'Spanish Main'			4);
INSERT INTO regions (region_id, name, area_id) VALUES (21  ,'Martinique',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (22  ,'Dutch Guianas'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (23  ,'Rio de la Plata'			4);
INSERT INTO regions (region_id, name, area_id) VALUES (24  ,'Virgin Islands'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (25  ,'St. Domingue'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (26  ,'North-east Brazil'			5);
INSERT INTO regions (region_id, name, area_id) VALUES (27  ,'Pernambuco',			5);
INSERT INTO regions (region_id, name, area_id) VALUES (29  ,'Bahamas',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (30  ,'South-east Brazil'			5);
INSERT INTO regions (region_id, name, area_id) VALUES (31  ,'San Domingo'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (32  ,'Puerto Rico'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (35  ,'Florida',			2  );
INSERT INTO regions (region_id, name, area_id) VALUES (36  ,'British Guiana'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (37  ,'French Guiana'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (48  ,'Trinidad',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (49  ,'Tortola',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (51  ,'Antigua',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (52  ,'Barbados',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (54  ,'Grenada',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (55  ,'Jamaica',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (56  ,'Montserrat',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (57  ,'St Lucia'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (58  ,'Tobago',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (59  ,'Nevis',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (60  ,'Bahia',			5);
INSERT INTO regions (region_id, name, area_id) VALUES (61  ,'Senegambia',			6);
INSERT INTO regions (region_id, name, area_id) VALUES (62  ,'Sierra Leone'			6);
INSERT INTO regions (region_id, name, area_id) VALUES (63  ,'Gold Coast'			6);
INSERT INTO regions (region_id, name, area_id) VALUES (64  ,'Windward Coast'			6);
INSERT INTO regions (region_id, name, area_id) VALUES (65  ,'Angola',			6);
INSERT INTO regions (region_id, name, area_id) VALUES (66  ,'South-east Africa'			6);
INSERT INTO regions (region_id, name, area_id) VALUES (67  ,'Indian Ocean isles'			7);
INSERT INTO regions (region_id, name, area_id) VALUES (78  ,'Dominica',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (80  ,'St Vincent'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (83  ,'USA unspecified'			2  );
INSERT INTO regions (region_id, name, area_id) VALUES (90  ,'St Kitts'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (92 ,'unspecified',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (93  ,'Gulf of Guinea Islands'			7);
INSERT INTO regions (region_id, name, area_id) VALUES (94 ,'unspecified',			5);
INSERT INTO regions (region_id, name, area_id) VALUES (95  ,'Spanish America unspecified'			4);
INSERT INTO regions (region_id, name, area_id) VALUES (96  ,'Spanish Caribbean unspedified'			3);
INSERT INTO regions (region_id, name, area_id) VALUES (98  ,'Cuba',			3);
INSERT INTO regions (region_id, name, area_id) VALUES (99  ,'Not specified' 0			);
